IN-517 refactor to work in aws properly
ministryofjustice/opg-data-casrec-migration pull request #74
Opened 2020-11-24 21:16 UTC by jamesrwarren

## Purpose

Make some stuff actually run in aws and make the layout more consistent.

## Approach

Wanted to add some extra bits to prove it works in aws to this one but think it will go in next ticket. This seems quite a self contained ticket as it is.

## Learning

NA
## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-11-25 15:06 UTC, jmackown requested changes

2020-11-26 09:10 UTC, jackgoodby reviewed
I've attached this to line 2 instead of line 4 duh. You know what I mean though

2020-11-26 09:29 UTC, jamesrwarren commented on .pre-commit-config.yaml
> +        args: ['--ignore=E402,F403,F405']
Done

2020-11-26 09:33 UTC, jackgoodby approved these changes

2020-11-26 09:59 UTC, merged